language: python
python:
  - "3.6"
services:
 - memcached
install: "pip install -r requirements.txt"
before_script:
 - echo "SECRET_KEY='abcdefghijklmnopqrstuvwxyz123456789'" > settings/local.py
script: "./manage.py test"
