# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='LT rating times 10'),
        ),
    ]
