# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20151115_1135'), ('blog', '0003_no_autoslug')]

    initial = True

    dependencies = [
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sourcename', models.CharField(db_index=True, max_length=100, unique=True)),
                ('orig_width', models.IntegerField()),
                ('orig_height', models.IntegerField()),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('frontimage', models.TextField(blank=True)),
                ('lang', models.CharField(db_index=True, max_length=2)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-posted_time'],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
